## We are going to learn numpy

#### this is a new headline

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3])
              

In [3]:
type(arr)

numpy.ndarray

In [4]:
arr.ndim

1

In [5]:
arr.shape

(3,)

In [6]:
arr = np.array([1, 2 , 3])

In [7]:
arr.shape

(3,)

In [8]:
arr.size

3

In [9]:
arr.dtype

dtype('int32')

In [10]:
a = np.array([[1, 2 , 3],[5,8,7]],dtype = 'float')

In [11]:
print(a)

[[1. 2. 3.]
 [5. 8. 7.]]


In [12]:
#creating numpy from tuple
b = np.array((1,2,3))
print(b)

[1 2 3]


In [13]:
c = np.zeros((5,6))
print(c)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [14]:
c1 = np.ones((5,6))

In [15]:
c1

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [16]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
np.arange?

In [18]:
f= np.arange(0,30,5)
print(f)

[ 0  5 10 15 20 25]


In [19]:
q = np.linspace(0,5,10)
print(q)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [20]:
e = np.random.random((2,2))

In [22]:
e

array([[0.2690711 , 0.25265167],
       [0.43101478, 0.38822783]])

In [23]:
arr = np.array([[1,2,3,4],[5,2,4,2],[1,2,0,1]])
newarr = arr.reshape(2,2,3)

In [24]:
newarr

array([[[1, 2, 3],
        [4, 5, 2]],

       [[4, 2, 1],
        [2, 0, 1]]])

In [25]:
newarr = arr.reshape(4,3)

In [26]:
newarr

array([[1, 2, 3],
       [4, 5, 2],
       [4, 2, 1],
       [2, 0, 1]])

In [27]:
#array indexing

arr = np.array([[-1,2,0,4],[4,-0.5,6,0],[2.6,0,7,8],[3,-7,4,2.0]])

In [37]:
arr[1::2,:3:2]

array([[4., 6.],
       [3., 4.]])

In [34]:
temp

array([[ 4. , -0.5,  6. ],
       [ 2.6,  0. ,  7. ],
       [ 3. , -7. ,  4. ]])

In [38]:
cond = arr>0
temp = arr[cond]

In [39]:
temp

array([2. , 4. , 4. , 6. , 2.6, 7. , 8. , 3. , 4. , 2. ])

In [45]:
a = np.array([[1,2,3],[3,4,5],[9,6,0]])
a+1

array([[ 2,  3,  4],
       [ 4,  5,  6],
       [10,  7,  1]])

In [41]:
a*3

array([ 3,  6, 15,  9])

In [42]:
a**2

array([ 1,  4, 25,  9], dtype=int32)

In [46]:
a.T

array([[1, 3, 9],
       [2, 4, 6],
       [3, 5, 0]])

In [47]:
a.max()

9

In [48]:
a.sum()

33

In [49]:
a.max(axis=1) #read row wise

array([3, 5, 9])

In [50]:
a.max(axis=0)

array([9, 6, 5])

In [51]:
a = np.array([[1,2],[3,4]])
b = np.array([[4,3],[2,1]])

In [52]:
a+b

array([[5, 5],
       [5, 5]])

In [53]:
a*b

array([[4, 6],
       [6, 4]])

In [54]:
a.dot(b)

array([[ 8,  5],
       [20, 13]])

In [55]:
#create a array of sine values
a1 = np.array([0,np.pi/2,np.pi])
print(np.sin(a1))

[0.0000000e+00 1.0000000e+00 1.2246468e-16]


In [56]:
a3 = np.array([0,1,2,3,])

In [57]:
np.exp(a3)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692])

In [58]:
np.sqrt(a3)

array([0.        , 1.        , 1.41421356, 1.73205081])

In [59]:
a4 = np.array([[1,2,3],[3,4,5],[9,6,0]])

In [61]:
np.sort(a4,axis=None)

array([0, 1, 2, 3, 3, 4, 5, 6, 9])

In [62]:
np.sort(a4,axis=1)

array([[1, 2, 3],
       [3, 4, 5],
       [0, 6, 9]])

In [63]:
np.sort(a4,axis=0,kind = 'mergesort')

array([[1, 2, 0],
       [3, 4, 3],
       [9, 6, 5]])

In [64]:
a4 = np.array([[1,2],
               [3,4]])
b4 = np.array([[5,6],
              [7,8]])

In [77]:
print(np.vstack((a4,b4)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [75]:
a4 = np.array([[1,2],
               [3,4]])
b4 = np.array([[5,6],
              [7,8]])

In [79]:
print(np.hstack((a4,b4)))

[[1 2 5 6]
 [3 4 7 8]]


In [72]:
c=[5,6]

In [80]:
np.column_stack((a,c))

array([[1, 2, 5],
       [3, 4, 6]])

In [81]:
np.concatenate((a,b),1)

array([[1, 2, 4, 3],
       [3, 4, 2, 1]])

In [82]:
np.split(a4,2)

[array([[1, 2]]), array([[3, 4]])]

In [83]:
np.hsplit(a4,2)

[array([[1],
        [3]]),
 array([[2],
        [4]])]

In [84]:
np.vsplit(a4,2)

[array([[1, 2]]), array([[3, 4]])]

In [85]:
np.min(a4)

1

In [86]:
np.min(a4,axis=0)

array([1, 2])

In [87]:
np.max(a,axis=1)

array([2, 4])

In [88]:
b = np.array([1,2,3,4,5])
m = sum(b)/5
print(m)

3.0


In [89]:
np.mean(b)

3.0

In [90]:
np.mean(a,axis=0)

array([2., 3.])

In [91]:
np.mean(a,axis=1)

array([1.5, 3.5])