In [1]:
import numpy as np

In [2]:
print(np.__version__)#version
print(np.show_config())

1.19.2
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/DELL/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/DELL/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/DELL/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/DELL/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/DELL/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/DELL/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/DELL/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/DELL/anaconda3\\Library\\include']
None


In [3]:
arr = np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
a = arr.size
b = arr.itemsize
print("{} bytes".format(a*b))

80 bytes


In [5]:
np.add?

In [6]:
arr = np.zeros(10)
arr[4] = 1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [7]:
arr = np.arange(10,50,5)
arr

array([10, 15, 20, 25, 30, 35, 40, 45])

In [8]:
np.flipud(arr)

array([45, 40, 35, 30, 25, 20, 15, 10])

In [9]:
arr = np.random.randint(0,9,(3,3))
arr

array([[2, 3, 4],
       [1, 0, 7],
       [8, 8, 2]])

In [10]:
arr = np.array([1,2,0,0,4,0])
ans = np.nonzero(arr)
ans

(array([0, 1, 4], dtype=int64),)

In [11]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
np.random.random((3,3,3))

array([[[5.94542116e-01, 2.29833304e-01, 6.18629349e-01],
        [6.00360427e-01, 9.95885976e-01, 7.13644497e-04],
        [6.87216807e-01, 2.03078976e-02, 7.15513026e-01]],

       [[9.35235154e-01, 1.58056520e-01, 5.75157937e-01],
        [5.93804171e-01, 7.57564525e-01, 3.30643157e-01],
        [5.86497212e-02, 6.21968032e-01, 4.93088959e-01]],

       [[4.17055606e-01, 3.99614500e-01, 1.48935565e-01],
        [9.44143651e-01, 4.14109601e-01, 8.33660568e-01],
        [9.59114568e-01, 4.58750079e-01, 5.32879752e-01]]])

In [16]:
arr = np.random.random((10,10))
a= np.max(arr)
b = np.min(arr)
print(a,b,sep = "\n")

0.9973917385909817
0.015876312604905407


In [17]:
arr = np.random.random((30))
ans = np.mean(arr)
ans

0.5377057797694936

In [18]:
ans = np.ones((5,5))
ans[1:-1,1:-1] = 0
ans

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
ans = np.ones((5,5))
np.pad(ans,pad_width=1,mode = 'constant',constant_values = 0)

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [20]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == (3 * 0.1))

nan
False
False
nan
True
False


In [24]:
ans = np.diag([1,2,3,4],-3)
ans

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0]])

In [25]:
ans = np.zeros((8,8),dtype=int)
ans[1::2,::2] = 1
ans[::2,1::2] = 1
ans

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [26]:
np.unravel_index(99,(6,7,8))

(1, 5, 3)

In [27]:
arr = [[0,1],[1,0]]
a=4
b=4
repetition = (a,b)
ans = np.tile(arr,repetition)
ans

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [34]:
arr = np.random.rand(5,5)
arr = (arr - np.mean(arr)) / np.std(arr)
arr

array([[-3.09065099e-01,  1.49088334e+00, -1.72844164e+00,
        -5.19354261e-01, -1.09286759e+00],
       [ 4.35900290e-01, -5.98264939e-01,  9.21627535e-01,
         1.06703119e+00,  2.86416451e-01],
       [ 3.27686314e-01, -1.60178763e+00, -6.91246915e-01,
         5.78119108e-04,  6.84480923e-01],
       [ 1.10736064e+00,  5.32031313e-01, -1.71188875e+00,
        -1.92240698e+00,  4.56501888e-01],
       [ 1.30802393e+00,  8.29705189e-01,  2.00834628e-01,
        -4.68556236e-01,  9.94818279e-01]])

In [35]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])

<ipython-input-35-b9f1a6f5df9c>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([("r", np.ubyte, 1),


In [36]:
a = np.random.random((5,3))
b=np.random.random((3,2))
print(np.dot(a,b))

[[1.04987288 1.0556608 ]
 [0.5117691  0.36381058]
 [0.65223166 0.90515664]
 [1.04714302 0.28895763]
 [0.16576984 0.11070425]]
